"""Add pause fields to Attendance model

Revision ID: f517609078c5
Revises: f4ea05d2b236
Create Date: 2025-09-05 11:03:01.108187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f517609078c5'
down_revision = 'f4ea05d2b236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paused', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pause_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resume_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('resume_time')
        batch_op.drop_column('pause_time')
        batch_op.drop_column('is_paused')

    # ### end Alembic commands ###
